# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xjItmZ5h0K4GKhx4ML16KEi-Dg-17UgO
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
data_train = pd.read_csv("data_wage_train.csv")

X = data_train.drop("wage", axis=1)
y = data_train["wage"]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.1, random_state=8)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
model = LinearRegression()

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_val_scaled)
mse = mean_squared_error(y_val, y_pred)
print("Mean Squared Error (MSE) en conjunto de validación:", mse)
data_test = pd.read_csv("data_test.csv")

X_test_scaled = scaler.transform(data_test)

predictions = model.predict(X_test_scaled)

predictions_df = pd.DataFrame({'Expected': predictions})
predictions_df['id'] = data_test.index
predictions_df = predictions_df[['id', 'Expected']]
predictions_df.to_csv("Maury31predictions013131.csv", index=False)